@startuml

sprite $netlify [64x56/16z] {
xTP50eD038NX1p7i_jUjjy4bKs__3VeDx2QOY-sG89pyclzxaPXt8GbU7KGysIbD-xuJraECpGiemccYXoPw43CXkVnM5k7MUBLjNw9esjKKyrwUwAk8B_93
N3N7AE0Df-hZkM8yqNwP-_Q_u52cWsmGzRtTFDcWJ_Si_J3j8OCmQCflwE_rQBHrRdXMeig8fo_TFzJSXxbnSFuavx7zcvs7FDXvo8FvUVFRt__z7W
}

ServiceIconColoring(netlify)
!define Netlify(_alias, _label) ServiceIcon(_alias, netlify, "#004848", Netlify, _label)

@enduml
