@startuml
!include ./values.puml

sprite $gke [64x64/16z] {
xPS7hgCX38JTxTp_mhiebaZ1OBtUHYNrWzypLFXQ-XEgHoNZ8quUE-c9zzXBzhZ4GOux73rEiXslSHRLE4L3LlCM7PKXShJan-nUbg56Kuv5TbrfspmLBpCy
PsTK34dhcESP56eZGrwwJ8gA06H5XdNtYHbU6sBVMwYBmZLYy5c8x38aVomy2pBCzfvii3exdWqo9ALFDLAP7G5F230RV-IjD8-knHh2K9ftGV0YGuabBv12
Ixx8q9Uyk5CsR_RCpmuubZmES5ZX1BhaFREl-16PZp8BFZ2Vh-A7TG0ddZSyrVmqq5_8I_AyuDFxv45s-O4zyip0OPZyU8iAvVW1VEHp_ElWqTRZts1Ag_cZ
qPa_WElvcyhvQrNtYzM1vaEjru_0q_gLFPxMhsM64yiKub77xICVUnPIP5TaE6sGvXQiBzc_YWnVT0IHDe_lSdu0RlBlTNu2wk3-VkV7bvzV-ndYEvxVpnNO
I-ylb_yAP_XQ-jC_
}

ServiceIconColoring(gke)
!define GKE(_alias, _label) ServiceIcon(_alias, gke, GCP_COLOR, GKE, _label)

@enduml
